name: ci

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-west-2
  # ECR_REPOSITORY: 358098103526.dkr.ecr.us-west-2.amazonaws.com/jerkytreats
  ECR_REPOSITORY: jerkytreats

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG_SHA: ${{ github.sha }}
          IMAGE_TAG_BRANCH: ${{ github.branch }}
          IMAGE_TAG_LATEST: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_SHA -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_BRANCH -t $ECR_REGISTRY/$ECR_REPOSITORY:$LATEST .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
          # echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
