on: [push]

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    name: Deploy via fleek on IPFS # THE FUTURE FAM THE FUTURE
    steps:
      - uses: actions/checkout@v2
      - name: Deploy site
        id: deploy
        uses: fleekhq/action-deploy@v1
        with:
          apiKey: ${{ secrets.FLEEK_API_KEY }}
      - name: Get the output url
        run: echo "Deploy url is ${{ steps.deploy.outputs.deployUrl }}"
